#!/usr/bin/env zsh
get_time_ms() {
  if command -v gdate >/dev/null 2>&1; then 
    gdate +%s%3N
  else
    date +%s%3N
  fi
}

started=$(get_time_ms)
source ~/.zsh_profile
finished=$(get_time_ms)
diff=$((finished-started))
echo " --> loaded zshrc in $diff milliseconds"
