#!/usr/bin/env bash
#
# Installs the dotfiles

if [[ ! -e ".git" ]]; then
  echo "cloning dotfiles into: $HOME/dotfiles ..."
  git clone git@github.com:jaredallard/dotfiles "$HOME/dotfiles"
  pushd "$HOME/dotfiles" >/dev/null 2>&1 || exit 1
fi

IGNORED_FILES=$(cat <<EOF
.git
install
README.md
bin
EOF
)

GLOBIGNORE=".:.."

echo "installing dotfiles ..."
for file in *; do
  grep -w "$file" <<<"$IGNORED_FILES" >/dev/null 2>&1
  if [[ $? == 0 ]]; then
    continue
  fi
  
  cp -Trv "$file" "$HOME/$file"
done

echo "done"

popd >/dev/null 2>&1
