#!/bin/bash

cd "$HOME/.config/i3lock/"
import -silent -window root window.png;
i3lock -c "#000000" &
convert window.png -scale 100% -blur 0x15 -scale 100% lock.png;
#convert lock.png -scale 10% -scale 1000% lock.png;
composite -gravity center pad.png lock.png lock.png;
killall i3lock
i3lock -i lock.png
